# Generated by Django 4.2.3 on 2023-07-31 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bot_API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recetas',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
