# Generated by Django 4.2.3 on 2023-07-31 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bot_API', '0002_recetas_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recetas',
            name='Titulo',
            field=models.CharField(max_length=200),
        ),
    ]
