# Generated by Django 4.2.3 on 2023-08-07 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bot_API', '0003_alter_recetas_titulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Predicciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=200)),
                ('Prediccion', models.TextField()),
                ('url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
